---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/intakes/{id}/measurements":
    post:
      summary: Creates a measurements
      tags:
      - Measurements
      parameters: []
      responses:
        '201':
          description: measurement created
          content: {}
        '422':
          description: measurement request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                units:
                  type: integer
              required:
              - units
  "/api/v1/intakes/{id}/measurements/{id}":
    get:
      summary: Retrieves a measurement
      tags:
      - Measurements
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: measurement found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
        '404':
          description: measurement not found
          content: {}
        '406':
          description: unsupported accept header
          content: {}
    delete:
      summary: Deletes a measurement
      tags:
      - Measurements
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: measurement found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
        '404':
          description: measurement not found
          content: {}
        '406':
          description: unsupported accept header
          content: {}
    patch:
      summary: Edits a measurement parameter
      tags:
      - Measurements
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: measurement found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  units:
                    type: integer
                required:
                - id
                - units
        '404':
          description: measurement not found
          content: {}
        '406':
          description: unsupported accept header
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
